#The classpath is the path where the Java Virtual Machine look for user-defined classes, packages and resources in Java programs.
#Setting the name for configuration server
#Using these names,only the entire spring cloud config server concept is going to work.
spring:
  application:
    name: "configserver"
#I have to communicate to my spring cloud config server that I have stored all these files in so and
  profiles:
    active: git
  #USE NATIVE PROFILE ONLY WHEN YOU ARE USING CLASSPATH OR FILEPATH
    #active: "native"   #  I'm mention native here because we store our configuration in a classpath [ the classpath is just a set of paths where the java compiler and the JVM must find needed classes to compile or execute other classes. ]
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/eazybytes/eazybytes-config.git"
          default-label: main # the github default branch
          timeout: 5 # exception should be display if the server is not connecting to github
          clone-on-start: true   #To start clone the repo at the start of the project
          force-pull: true # By mentioning this force-pull as true. We are telling to override all the local changes whenever you are trying to start or restart our config server. This will make sure your config server always reading the properties from the master location which is GitHub repo.
  rabbitmq:
    host: "localhost"
    port: 5672
    stream:
      username: "guest"
      password: "guest"
        #native:
        # search-locations: "file:///Users//ibitoye/Documents//eazybytes/config"
        #search-locations: "classpath:/config"

server:
  port: 8071
  # we need this management properties for our webhook to automatic refresh the microservice instantance and also to expose actuator api path
management:
  endpoints:
    web:
      exposure:
        include: "*"